language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp engine/config/parameters.yml.travis engine/config/parameters.yml
  - composer selfupdate
  - composer install
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test
  # - bin/console doctrine:fixtures:load -n --env=test

script:
  - composer test