services:
    tekkl_user.handler.authentication_success:
      class:     Tekkl\Bundle\UserBundle\Security\Http\Authentication\AuthenticationSuccessHandler
      arguments: ['@lexik_jwt_authentication.jwt_manager', '@event_dispatcher', '%tekkl_user.jwt.cookie.name%', '%tekkl_user.jwt.cookie.ttl%', '%tekkl_user.jwt.authorization_header.prefix%', '%tekkl_user.jwt.authorization_header.name%' ]
      tags:
        - { name: monolog.logger, channel: security }

    tekkl_user.handler.authentication_failure:
      class:     Tekkl\Bundle\UserBundle\Security\Http\Authentication\AuthenticationFailureHandler
      arguments: ['@event_dispatcher',  '%tekkl_user.jwt.cookie.name%']
      tags:
        - { name: monolog.logger, channel: security }