api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
    
tekkl_user:
    resource: "@TekklUserBundle/Resources/config/routing.yml"
    prefix:   /api/user/

app:
    resource: "@TekklAppBundle/Controller/"
    type:     annotation




