api_login_check:
    path: /api/login_check
    
tekkl_user:
    resource: "@TekklUserBundle/Resources/config/routing.yml"
    prefix:   /api/user/

app:
    resource: "@TekklAppBundle/Controller/"
    type:     annotation




